apiVersion: v1
kind: Secret
metadata:
    name: "{{ .Values.appName}}-secret"
    namespace: {{ .Release.Namespace }}
    labels:
      app: {{.Values.labels.app}}
data:
  API_KEY: {{ .Values.API_KEY | b64enc }}