apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.labels.app}}
  name: "{{ .Values.appName}}-metrics-service"
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    app: {{.Values.labels.app}}